/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.Ctrl_Proveedor;
import java.awt.Color;
import java.awt.Dimension;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import modelo.Proveedor;

/**
 *
 * @author saduj
 */
public class InterProveedor extends javax.swing.JInternalFrame {

    public InterProveedor() {
        initComponents();

        this.setSize(new Dimension(400, 300));
        this.setTitle("Nuevo Proveedor");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_razonSocial = new javax.swing.JTextField();
        txt_ruc = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        jButton_guardar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ruc:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 80, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Razon  Social:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 110, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txt_razonSocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_razonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_razonSocialKeyPressed(evt);
            }
        });
        getContentPane().add(txt_razonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        txt_ruc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_rucKeyPressed(evt);
            }
        });
        getContentPane().add(txt_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        txt_telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyPressed(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        txt_direccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));

        jButton_guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, 30));

        jLabel_wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed

        Proveedor proveedor = new Proveedor();
        Ctrl_Proveedor controlProveedor = new Ctrl_Proveedor();
        String razon_social = txt_razonSocial.getText().trim();
        String ruc = txt_ruc.getText().trim();
        String email = txt_email.getText().trim();
        String telefono = txt_telefono.getText().trim();
        String direccion = txt_direccion.getText().trim();

        if (!txt_razonSocial.getText().isEmpty() && !txt_ruc.getText().isEmpty() && !txt_email.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Correcto");
            if (!controlProveedor.existeProveedor(txt_ruc.getText().trim())) {

                proveedor.setRazon_social(txt_razonSocial.getText().trim());
                proveedor.setEmail(txt_email.getText().trim());
                if (validarCampo(ruc, 11)) {
                    proveedor.setRuc(ruc);

                    if (validarCampo(telefono, 9)) {
                        proveedor.setTelefono(telefono);
                        proveedor.setDireccion(txt_direccion.getText().trim());
                        proveedor.setEstado(1);
                        if (validarCorreoElectronico(email) && tieneExtension(email)) {

                            if (controlProveedor.guardar(proveedor)) {
                                JOptionPane.showMessageDialog(null, "Registro guardado");
                                this.Limpiar();
                            } else {
                                JOptionPane.showMessageDialog(null, "Error al guardar");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "El campo email no es valido");
                            this.Limpiar();
                            txt_razonSocial.setText(razon_social);
                            txt_ruc.setText(ruc);
                            txt_email.setText("");
                            txt_direccion.setText(direccion);
                            txt_email.setBackground(Color.red);
                            txt_telefono.setText(telefono);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El campo Telefono esta incorrecto");
                        this.Limpiar();
                        txt_razonSocial.setText(razon_social);
                        txt_ruc.setText(ruc);
                        txt_email.setText(email);
                        txt_direccion.setText(direccion);
                        txt_telefono.setBackground(Color.red);
                    }
                    /*Juan-----------------------------------------------------*/
                } else {
                    JOptionPane.showMessageDialog(null, "El campo RUC esta incorrecto");
                    this.Limpiar();
                    txt_razonSocial.setText(razon_social);
                    txt_email.setText(email);
                    txt_telefono.setText(telefono);
                    txt_direccion.setText(direccion);
                    txt_ruc.setBackground(Color.red);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El proveedor ya se encuentra registrado");
                txt_razonSocial.setBackground(Color.white);
                txt_ruc.setBackground(Color.white);
                txt_email.setBackground(Color.white);
                txt_telefono.setBackground(Color.white);
                txt_direccion.setBackground(Color.white);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
            txt_razonSocial.setBackground(Color.red);
            txt_ruc.setBackground(Color.red);
            txt_email.setBackground(Color.red);
            txt_telefono.setBackground(Color.red);
            txt_direccion.setBackground(Color.red);
        }
        /*this.Limpiar();*/

    }//GEN-LAST:event_jButton_guardarActionPerformed

    public static boolean validarCorreoElectronico(String correoElectronico) {
        String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(correoElectronico);
        return matcher.matches();
    }
    public static boolean tieneExtension(String correoElectronico) {
        String regex = ".*\\.[a-zA-Z]{2,}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(correoElectronico);
        return matcher.matches();
    }

    private void txt_razonSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_razonSocialKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        validarInputs(1, c, txt_razonSocial);
    }//GEN-LAST:event_txt_razonSocialKeyPressed

    private void txt_rucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        validarInputs(2, c, txt_ruc);
    }//GEN-LAST:event_txt_rucKeyPressed

    private void txt_telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        validarInputs(2, c, txt_telefono);
    }//GEN-LAST:event_txt_telefonoKeyPressed
    void validarInputs(int tipo, char c, javax.swing.JTextField input) {
        switch (tipo) {
            case 1:
                input.setEditable(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c));
                break;
            case 2:
                input.setEditable(Character.isDigit(c) || Character.isWhitespace(c) || Character.isISOControl(c));
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_razonSocial;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
    /**
     * limpiar campos
     */
    private void Limpiar() {
        txt_razonSocial.setText("");
        txt_ruc.setText("");
        txt_email.setText("");
        txt_telefono.setText("");
        txt_direccion.setText("");
        txt_razonSocial.setBackground(Color.white);
        txt_ruc.setBackground(Color.white);
        txt_email.setBackground(Color.white);
        txt_telefono.setBackground(Color.white);
        txt_direccion.setBackground(Color.white);
    }

    /*Procedimeinto de Juan --Validar campo*/
    public static boolean validarCampo(String dato, int n) {
        if (dato.length() == n && dato.matches("\\d+")) {
            return true;
        } else {
            return false;
        }
    }

}
